match_array_data  = [
    {"name": "inside_wall",
     "setup": ((1, 1, 1),
               (1, 1, 1),
               (1, 1, 1))},
    {"name": "top_edge",
     "setup": ((0, 0, 0),
               (1, 1, 1),
               (1, 1, 1))},
    {"name": "top_edge",
     "setup": ((0, 0, 0),
               (1, 1, 1),
               (1, 1, 1))},
    {"name": "top_edge",
     "setup": ((0, 0, 1),
               (1, 1, 1),
               (1, 1, 1))},
    {"name": "top_edge",
     "setup": ((1, 0, 0),
               (1, 1, 1),
               (1, 1, 1))},
    {"name": "bottom_edge",
     "setup": ((1, 1, 1),
               (1, 1, 1),
               (0, 0, 0))},
    {"name": "bottom_edge",
     "setup": ((1, 1, 1),
               (1, 1, 1),
               (1, 0, 0))},
    {"name": "bottom_edge",
     "setup": ((1, 1, 1),
               (1, 1, 1),
               (1, 0, 1))},
    {"name": "bottom_edge",
     "setup": ((1, 1, 1),
               (1, 1, 1),
               (0, 0, 1))},
    {"name": "left_edge",
     "setup": ((0, 1, 1),
               (0, 1, 1),
               (0, 1, 1))},
    {"name": "left_edge",
     "setup": ((1, 1, 1),
               (0, 1, 1),
               (0, 1, 1))},
    {"name": "left_edge",
     "setup": ((0, 1, 1),
               (0, 1, 1),
               (1, 1, 1))},
    {"name": "right_edge",
     "setup": ((1, 1, 0),
               (1, 1, 0),
               (1, 1, 0))},
    {"name": "right_edge",
     "setup": ((1, 1, 1),
               (1, 1, 0),
               (1, 1, 0))},
    {"name": "right_edge",
     "setup": ((1, 1, 1),
               (1, 1, 0),
               (1, 1, 1))},
    {"name": "right_edge",
     "setup": ((1, 1, 0),
               (1, 1, 0),
               (1, 1, 1))},
    {"name": "top_left_corner",
     "setup": ((0, 0, 0),
               (0, 1, 1),
               (0, 1, 1))},
    {"name": "top_right_corner",
     "setup": ((0, 0, 0),
               (1, 1, 0),
               (1, 1, 0))},
    {"name": "bottom_left_corner",
     "setup": ((0, 1, 1),
               (0, 1, 1),
               (0, 0, 0))},
    {"name": "bottom_right_corner",
     "setup": ((1, 1, 0),
               (1, 1, 0),
               (0, 0, 0))},
    {"name": "bottom_ns_column",
     "setup": ((0, 1, 0),
               (0, 1, 0),
               (0, 0, 0))},
    {"name": "middle_ns_column",
     "setup": ((0, 1, 0),
               (0, 1, 0),
               (0, 1, 0))},
    {"name": "middle_ns_column",
     "setup": ((1, 1, 0),
               (0, 1, 0),
               (1, 1, 1))},
    {"name": "middle_ns_column",
     "setup": ((1, 1, 0),
               (0, 1, 0),
               (0, 1, 0))},
    {"name": "middle_ns_column",
     "setup": ((0, 1, 1),
               (0, 1, 0),
               (1, 1, 0))},
    {"name": "middle_ns_column",
     "setup": ((1, 1, 0),
               (0, 1, 0),
               (1, 1, 0))},
    {"name": "middle_ns_column",
     "setup": ((0, 1, 0),
               (0, 1, 0),
               (1, 1, 0))},
    {"name": "middle_ns_column",
     "setup": ((0, 1, 0),
               (0, 1, 0),
               (0, 1, 1))},
    {"name": "middle_ns_column",
     "setup": ((0, 1, 0),
               (0, 1, 0),
               (1, 1, 1))},
    {"name": "middle_ns_column",
     "setup": ((0, 1, 1),
               (0, 1, 0),
               (0, 1, 0))},
    {"name": "middle_ns_column",
     "setup": ((1, 1, 1),
               (0, 1, 0),
               (0, 1, 0))},
    {"name": "middle_ns_column",
     "setup": ((0, 1, 1),
               (0, 1, 0),
               (0, 1, 1))},
    {"name": "middle_ns_column",
     "setup": ((1, 1, 0),
               (0, 1, 0),
               (0, 1, 1))},
    {"name": "top_ns_column",
     "setup": ((0, 0, 0),
               (0, 1, 0),
               (0, 1, 0))},
    {"name": "left_ew_column",
     "setup": ((0, 0, 0),
               (0, 1, 1),
               (0, 0, 0))},
    {"name": "middle_ew_column",
     "setup": ((0, 0, 0),
               (1, 1, 1),
               (0, 0, 0))},
    {"name": "middle_ew_column",
     "setup": ((0, 0, 0),
               (1, 1, 1),
               (1, 0, 1))},
    {"name": "middle_ew_column",
     "setup": ((1, 0, 0),
               (1, 1, 1),
               (1, 0, 0))},
    {"name": "middle_ew_column",
     "setup": ((0, 0, 0),
               (1, 1, 1),
               (1, 0, 0))},
    {"name": "middle_ew_column",
     "setup": ((1, 0, 0),
               (1, 1, 1),
               (0, 0, 1))},
    {"name": "middle_ew_column",
     "setup": ((1, 0, 1),
               (1, 1, 1),
               (0, 0, 1))},
    {"name": "middle_ew_column",
     "setup": ((0, 0, 1),
               (1, 1, 1),
               (1, 0, 0))},
    {"name": "middle_ew_column",
     "setup": ((1, 0, 0),
               (1, 1, 1),
               (1, 0, 0))},
    {"name": "middle_ew_column",
     "setup": ((0, 0, 1),
               (1, 1, 1),
               (0, 0, 0))},
    {"name": "middle_ew_column",
     "setup": ((1, 0, 0),
               (1, 1, 1),
               (0, 0, 0))},
    {"name": "middle_ew_column",
     "setup": ((0, 0, 1),
               (1, 1, 1),
               (0, 0, 1))},
    {"name": "middle_ew_column",
     "setup": ((0, 0, 0),
               (1, 1, 1),
               (0, 0, 1))},
    {"name": "right_ew_column",
     "setup": ((0, 0, 0),
               (1, 1, 0),
               (0, 0, 0))},
    {"name": "corner_1",
     "setup": ((1, 1, 1),
               (1, 1, 1),
               (1, 1, 0))},
    {"name": "corner_2",
     "setup": ((1, 1, 1),
               (1, 1, 1),
               (0, 1, 1))},
    {"name": "corner_3",
     "setup": ((1, 1, 0),
               (1, 1, 1),
               (1, 1, 1))},
    {"name": "corner_4",
     "setup": ((0, 1, 1),
               (1, 1, 1),
               (1, 1, 1))},
    {"name": "column_turn_1",
     "setup": ((0, 0, 0),
               (0, 1, 1),
               (0, 1, 0))},
    {"name": "column_turn_2",
     "setup": ((0, 0, 0),
               (1, 1, 1),
               (0, 1, 0))},
    {"name": "column_turn_3",
     "setup": ((0, 0, 0),
               (1, 1, 0),
               (0, 1, 0))},
    {"name": "column_turn_4",
     "setup": ((0, 1, 0),
               (0, 1, 1),
               (0, 1, 0))},
    {"name": "column_turn_5",
     "setup": ((0, 1, 0),
               (1, 1, 1),
               (0, 1, 0))},
    {"name": "column_turn_6",
     "setup": ((0, 1, 0),
               (1, 1, 0),
               (0, 1, 0))},
    {"name": "column_turn_7",
     "setup": ((0, 1, 0),
               (0, 1, 1),
               (0, 0, 0))},
    {"name": "column_turn_8",
     "setup": ((0, 1, 0),
               (1, 1, 1),
               (0, 0, 0))},
    {"name": "column_turn_9",
     "setup": ((0, 1, 0),
               (1, 1, 0),
               (0, 0, 0))},
    {"name": "solo",
     "setup": ((0, 0, 0),
               (0, 1, 0),
               (0, 0, 0))},
    {"name": "ew_corner_1",
     "setup": ((0, 0, 0),
               (1, 1, 1),
               (1, 1, 0))},
    {"name": "ew_corner_2",
     "setup": ((0, 0, 0),
               (1, 1, 1),
               (0, 1, 1))},
    {"name": "ew_corner_3",
     "setup": ((1, 1, 0),
               (1, 1, 1),
               (0, 0, 0))},
    {"name": "ew_corner_4",
     "setup": ((0, 1, 1),
               (1, 1, 1),
               (0, 0, 0))},
    {"name": "ns_corner_1",
     "setup": ((0, 1, 1),
               (0, 1, 1),
               (0, 1, 0))},
    {"name": "ns_corner_2",
     "setup": ((1, 1, 0),
               (1, 1, 0),
               (0, 1, 0))},
    {"name": "ns_corner_3",
     "setup": ((0, 1, 0),
               (0, 1, 1),
               (0, 1, 1))},
    {"name": "ns_corner_4",
     "setup": ((0, 1, 0),
               (1, 1, 0),
               (1, 1, 0))},
    {"name": "corners_nw_ne",
     "setup": ((0, 1, 0),
               (1, 1, 1),
               (1, 1, 1))},
    {"name": "corners_sw_se",
     "setup": ((1, 1, 1),
               (1, 1, 1),
               (0, 1, 0))},
    {"name": "corners_nw_sw",
     "setup": ((0, 1, 1),
               (1, 1, 1),
               (0, 1, 1))},
    {"name": "corners_ne_se",
     "setup": ((1, 1, 0),
               (1, 1, 1),
               (1, 1, 0))},
    {"name": "corners_ne_se_sw",
     "setup": ((1, 1, 0),
               (1, 1, 1),
               (0, 1, 0))},
    {"name": "corners_nw_se",
     "setup": ((0, 1, 1),
               (1, 1, 1),
               (1, 1, 0))},
]

def match_array(array_to_match):
    for item in match_array_data:
        if all(list(row1) == list(row2) for row1, row2 in zip(item['setup'], array_to_match)):
            return item['name']

    return None

# test_array = [[0, 1, 0],
#               [1, 1, 1],
#               [1, 1, 1]]

# result = match_array(test_array)
# print(f"Matched: {result}")